name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./geoscratch
      - run: sh ./geoscratch/install.sh
      - run: npm run build
      - name: npm install under geoscratch
        run: npm install
        working-directory: ./geoscratch
      - name: Build geoscratch.mjs for xcratch
        run: npm run build
        working-directory: ./geoscratch
      - name: Copy geoscratch.mjs to build folder
        run: cp ./geoscratch/dist/geoscratch.mjs ./build
      - name: Copy sample sb3 files to build folder
        run: cp ./geoscratch/sample_projects/xcratch/*.sb3 ./build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: 'gh-pages'
          folder: './build/'
          target-folder: './'
