name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./geolonia2scratch
      - run: sh ./geolonia2scratch/install.sh
      - run: npm run build
      - name: npm install under geolonia2scratch
        run: npm install
        working-directory: ./geolonia2scratch
      - name: Build geolonia2scratch.mjs for xcratch
        run: npm run build
        working-directory: ./geolonia2scratch
      - name: Copy geolonia2scratch.mjs to build folder
        run: cp ./geolonia2scratch/dist/geolonia2scratch.mjs ./build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: 'gh-pages'
          folder: './build/'
          target-folder: './'
