name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./geolonia2scratch
      - run: sed -i s/YYOUR\-API\-KEY/${{ secrets.GEOLONIA_API_KEY }}/g ./geolonia2scratch/scratch-vm/src/extensions/scratch3_geolonia2scratch/index.js
      - run: sh ./geolonia2scratch/install.sh
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
