name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./geo-scratch
      - run: sh ./geo-scratch/install.sh
      - run: npm run build
      - name: npm install under geo-scratch
        run: npm install
        working-directory: ./geo-scratch
      - name: Build geo-scratch.mjs for xcratch
        run: npm run build
        working-directory: ./geo-scratch
      - name: Copy geo-2scratch.mjs to build folder
        run: cp ./geo-scratch/dist/geo-scratch.mjs ./build
      - name: Copy sample.sb3 to build folder
        run: cp ./geo-scratch/sample_projects/xcratch/sample.sb3 ./build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: 'gh-pages'
          folder: './build/'
          target-folder: './'
